name: Docker Image Build

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'my-app/**'

  pull_request:
    branches: [ "dev" ]
    paths:
      - 'my-app/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up variables
      id: vars
      run: echo ::set-output name=tag::$(git describe --tags --always)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./my-app
        push: true
        tags: |
          tawfiq58/my-app:${{ steps.vars.outputs.tag }}

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Package and release charts
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: ./infra/k8s/helm/frontend
        config: |
          image.tag=${{ steps.vars.outputs.tag }}
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        