name: Docker Image Build

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'my-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up variables
        id: vars
        run: echo ::set-output name=tag::$(git describe --tags --always)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tawfiq58/my-app:${{ steps.vars.outputs.tag }}

