name: Update Helm Chart

on:
  push:
    branches: [ "dev" ]

jobs:
  push_chart:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Second Repository
        uses: actions/checkout@v3
        with:
          repository: tawfiqh58/my-chart
          ref: main
          path: my-chart
      
      - name: Set up variables
        id: vars
        run: echo ::set-output name=tag::$(git describe --tags --always)

      - name: Update Helm Chart
        run: |
          cd my-chart/charts/my-chart
          CURRENT_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}')
          MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d'.' -f3)
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" Chart.yaml
          GENERATED_HASH=$(cat $GITHUB_EVENT_PATH | jq -r '.after')
          sed -i "s/appVersion:.*/appVersion: $GENERATED_HASH/" Chart.yaml
          cat Chart.yaml

      
      - name: Push to Another Repository
        run: |
          cd my-chart
          git add .
          git config --global user.name "tawfiqh58"
          git config --global user.email "tawfiqhasan58@gmail.com"
          git remote add destination_repo https://github.com/tawfiqh58/my-chart.git
          git push destination_repo HEAD:main --force
        env:
          ACCESS_TOKEN: ${{ secrets.CHART_REPO_ACCESS_TOKEN }}
          GIT_ASKPASS: /usr/bin/true
          GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./my-app
          push: true
          tags: |
            tawfiq58/my-app:${{ steps.vars.outputs.tag }}